# Reformat python scripts in this repository using black
# and reformat shell scripts in this repository using shfmt
name: Reformat python scripts

on: 
  push:
    branches: ["**"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Format-python-scripts
        run: | 
          sudo apt install -y black shfmt
          black ./
          shfmt -l -w ./
      - name: Commit new documentation to branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Python and bash scripts reformatted   
          branch: main
