# Reformat python scripts in this repository using black
# and reformat shell scripts in this repository using shfmt
name: Run charge exchange unit tests

on: 
  push:
    branches: ["**"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run-unit-tests
        run: | 
          sudo apt update -y 
          sudo apt install -y python3.11 python3-pip
          python3.11 -m pip install matplotlib==3.8.0
          python3.11 -m pip install numpy==1.25.2
          python3.11 -m pip install scipy==1.9.3
          python3.11 -m unittests
          RESULT=$?
          if [[ ${RESULT} -ne 0 ]]; then
          printf "Tests failed to pass"
          exit ${RESULT}
          fi
